### ISSUE TITLE
Redirect loop case

### ISSUE THREAD

**Issue by misulicus** [easydigitaldownloads/edd-conditional-success-redirects#12]
If the Success Page in EDD is set to the same page as a custom redirect rule the customer is left in an endless redirect loop which at some point will error out.

@mintplugins tracked it down and i believe something like below on line 109 here should do the trick: 
https://github.com/easydigitaldownloads/edd-conditional-success-redirects/blob/master/includes/class-process-redirects.php#L109

````
$custom_redirect_url = $this->get_redirect();
$edd_success_page_url = get_permalink( edd_get_option( 'success_page' ) );

if ( $custom_redirect_url == $edd_success_page_url ) {
         return;
}
````

**Comment by pippinsplugins** [comment]
@mintplugins did you test with PayPal Express and a complete purchase process?

**Comment by pippinsplugins** [comment]
Great! Please go ahead and merge and deploy the update @mintplugins
