### ISSUE TITLE
Does not redirect when purchased from Buy Now through PayPal Standard

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-conditional-success-redirects#6]
When the purchase button is a Buy Now button for PayPal Standard, the redirect does not work after the purchase.

Redirects after Buy Now purchases seem to work just fine with other gateways like Stripe. And Add to Cart PayPal Standard is still working fine. 

It's just PayPal Standard Buy Now that doesn't properly redirect.

Relevant ticket: https://secure.helpscout.net/conversation/303233360/50680/?folderId=321418

**Comment by SDavisMedia** [comment]
Any clue why that'd happen, @sumobi?

**Comment by sumobi** [comment]
@SDavisMedia Oops missed this, will have a look at soon as I can!

**Comment by sumobi** [comment]
@SDavisMedia. I was able to replicate this also. Can you test the issue/6 branch let me know if this works for you? https://github.com/easydigitaldownloads/edd-conditional-success-redirects/tree/issue/6

**Comment by SDavisMedia** [comment]
@sumobi replicated again and confirmed fixed on `issue/6`. :+1:

**Comment by sumobi** [comment]
Woot, I'll go ahead and deploy an update, will leave you a note on the ticket once that's done.

**Comment by sumobi** [comment]
Fixed via https://github.com/easydigitaldownloads/edd-conditional-success-redirects/commit/cd3d93dfa85074d023f93e5bb7ca3853c332c50e

**Comment by SDavisMedia** [comment]
Thanks, man!
